In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim

In [2]:
v = [1,2,3]
print(type(v))
v_tensor = torch.Tensor(v)
print(v_tensor)

<class 'list'>
tensor([1., 2., 3.])


In [3]:
m23 = [[1,2,3],[4,5,6]]
m23tensor = torch.Tensor(m23)
print(m23tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
m3x3x3 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
          [[10, 11, 12],[13, 14, 15], [16, 17, 18]],
            [[19, 20, 21],[22, 23, 24], [25, 26, 27]]]
m3x3x3_tensor = torch.Tensor(m3x3x3)
print(m3x3x3_tensor)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]],

        [[19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.]]])


In [6]:
m4x3x3x3_tensor = torch.randn((4, 3, 3, 3))
m4x3x3x3_tensor.shape
print(m4x3x3x3_tensor)

tensor([[[[ 7.5108e-01, -7.8931e-01,  1.2143e-01],
          [ 1.1423e+00, -6.5110e-01, -1.1447e+00],
          [ 1.4818e-01,  1.2126e-01,  1.7980e-01]],

         [[-2.6266e-01,  7.6799e-01,  2.6699e-01],
          [ 1.5497e-01,  2.4484e-01, -1.7217e+00],
          [-2.0127e-03,  2.7179e-01,  8.3419e-01]],

         [[ 8.2753e-01,  1.3777e+00, -5.6957e-01],
          [-5.9316e-02,  1.3229e-01,  5.0006e-01],
          [ 1.4417e+00,  5.7883e-01, -1.0466e+00]]],


        [[[ 7.4622e-03, -2.7361e-02,  1.9816e-01],
          [-1.9891e-01, -1.3047e-01, -1.4295e+00],
          [ 5.6228e-01, -5.5411e-01, -2.3848e-01]],

         [[ 5.4759e-02,  1.0242e+00,  5.5690e-01],
          [ 2.3264e-01, -4.9060e-01, -2.1514e-01],
          [-5.9539e-01,  1.1996e+00, -3.5652e-01]],

         [[ 1.0944e+00, -3.4007e-01,  2.3784e+00],
          [ 8.7120e-01,  3.2855e-01,  1.0011e+00],
          [ 7.1025e-01, -5.0203e-01,  1.1738e+00]]],


        [[[ 8.0532e-02,  7.6014e-01,  3.6273e-01],
          [ 1.4

In [7]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,5,6])
print(x)
print(y)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [8]:
w = torch.matmul(x,y)
print(w)

tensor(32.)


In [9]:
x_1 = torch.randn(2,5)
print(x_1)

tensor([[-0.3410, -0.3857, -0.2048, -0.5992, -0.1972],
        [ 1.5291,  0.3651, -1.3025,  0.0493,  0.0080]])


In [10]:
y_1 = torch.randn(3,5)
print(y_1)

tensor([[ 0.1229, -0.3256,  0.7657,  0.4561,  2.0987],
        [ 0.3647, -0.4510, -2.2366, -1.3771,  0.1332],
        [ 1.3881, -1.5048, -0.0782, -0.9958,  0.0076]])


In [11]:
z_1 = torch.cat([x_1, y_1])
print(z_1)

tensor([[-0.3410, -0.3857, -0.2048, -0.5992, -0.1972],
        [ 1.5291,  0.3651, -1.3025,  0.0493,  0.0080],
        [ 0.1229, -0.3256,  0.7657,  0.4561,  2.0987],
        [ 0.3647, -0.4510, -2.2366, -1.3771,  0.1332],
        [ 1.3881, -1.5048, -0.0782, -0.9958,  0.0076]])


In [14]:
# Concatenate columns:
x_2 = torch.randn(2, 3)
print(x_2)
y_2 = torch.randn(2, 5)
print(y_2)

tensor([[ 0.3183, -0.8033,  0.5093],
        [-1.3512,  0.5032, -0.4501]])
tensor([[-1.4570,  0.2930,  0.2768,  0.7751, -0.2414],
        [ 1.2003, -0.4128,  0.7608, -0.8718, -0.5258]])


In [15]:
# second arg specifies which axis to concat along. Here we select 1 (columns). It's attaching the columns.
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

tensor([[ 0.3183, -0.8033,  0.5093, -1.4570,  0.2930,  0.2768,  0.7751, -0.2414],
        [-1.3512,  0.5032, -0.4501,  1.2003, -0.4128,  0.7608, -0.8718, -0.5258]])


In [16]:
x = torch.randn(64000, 3, 28, 28)
x_reshape = x.view(32, -1, 3, 28, 28)
print(x_reshape.shape)

torch.Size([32, 2000, 3, 28, 28])


In [17]:
x = autograd.Variable(torch.Tensor([1,2,3]), requires_grad = True)
print(x.data)

tensor([1., 2., 3.])


In [18]:
y = autograd.Variable(torch.Tensor([4, 5, 6]), requires_grad=True)

# With autograd.Variable you can also perform all the same operations you did with tensors
z = x + y
print(z.data)

tensor([5., 7., 9.])


In [19]:
#  w knows also that it's result of addition of z lements (AddBackward)
operation = z.grad_fn
print(operation)

In [20]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


In [21]:
s.backward(retain_graph=True)


In [22]:
print(x)
print(x.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 1., 1.])


In [23]:
print(y)
print(y.grad)

tensor([4., 5., 6.], requires_grad=True)
tensor([1., 1., 1.])


In [25]:
m_tensor = torch.randn((5, 4, 4, 4))
m_tensor[0].shape

torch.Size([4, 4, 4])

In [26]:
x = torch.randn(4, 3)
y = torch.randn(3, 4)
z = torch.cat([x, y], 1)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 4 and 3 in dimension 0 at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\aten\src\th\generic/THTensorMoreMath.cpp:1307